version: 2
updates:
  # Enable version updates for dependencies
  - package-ecosystem: "pip"
    directory: "/"
    # Check for updates daily
    schedule:
      interval: "daily"
    # Raise pull requests for version updates
    # to pip against the `feature/depend-a-bot` branch
    target-branch: "feature/depend-a-bot"
    # Labels on pull requests for version updates only
    labels: "pip dependencies"
