[project]
name = "ai4eu_server_demo"
description = "A containerized demo application for AI on demand (previously AI4EU) "
version = "0.2.20230331"
authors = [

    { name = "Antonis Gianios"},
    { name = "Íñigo Aréjula Aísa"},
    { name = "Jos van der Velde", email = "j.d.v.d.velde@tue.nl"},
    { name = "Pieter Gijsbers", email = "p.gijsbers@tue.nl"},
    { name = "Giannis Mouchakis"},
]
dependencies = [
    "sqlalchemy==2.0.0b4",
    "bibtexparser",
    "datasets",
    "fastapi",
    "uvicorn",
    "requests",
    "mysqlclient",
    "oic",
    "python-keycloak",
    "python-dotenv",
    "pydantic",
    "pydantic_schemaorg",
    "python-dateutil",
    "httpx"
]
readme = "README.md"

[project.optional-dependencies]
dev = [
    "types-python-dateutil",
    "pytest",
    "pre-commit",
    "responses",
    "starlette"
]

[tool.black]
line-length = 100