# Configures the REST API

# Information on which database to connect to
[database]
host = "172.17.0.2"
port = 3306
database = "aiod"
username = "root"
password = "ok"

# Additional options for development
[dev]
reload = true
