name: Docker Image CI and pytest

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.11"]
    runs-on: ubuntu-lates

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --tag ai4eu_server_demo:latest -f Dockerfile .

    - name: Check for dockerenv file
      run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
  
  # test:
  #   strategy:
  #     matrix:
  #       python-version: ["3.11"]
  #   runs-on: ubuntu-latest
  #   container: ai4eu_server_demo:latest
  #   steps:

  #     - uses: actions/checkout@v3
  #     - name: Set up Python ${{ matrix.python-version }} 
  #       uses: actions/setup-python@v3
  #       with:
  #         python-version: ${{ matrix.python-version }}  
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install .
  #         python -m pip install ".[dev]"
  #         pre-commit install
          
  #     - name: pre-commit check
  #       run: |
  #         pre-commit run --all
      
  #     - name: Test with pytest
  #       run: |
  #         pytest ./src/tests/ 
    


