name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --tag ai4eu_server_demo:latest -f Dockerfile .

    # create mysql-network 
    - run: docker network create sql-network
    
    #Start up sqlserver
    - name: Built mysql server
      run: docker run --network sql-network -it --rm -p 8000:8000 --name apiserver ai4eu_server_demo


