name: Docker Image CI 

on:
  push:
    paths:
      - '.github/workflows/docker-image.yml'
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  built:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build --tag ai4eu_server_demo:latest -f Dockerfile .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ai4eu_server_demo
          username: ${{ github.actor }}
          password: ${{ secrets.github_token }}
          
      - name: Push the docker Image
        run: | 
          docker push ai4eu_server_demo
          docker tag ai4eu_server_demo:latest
          docker push ai4eu_server_demo:latest
  
  
    


