name: Built docker image and run tests

# This workflow will built docker image and run tests inside the container.
# This workflow is only executed when a push is made in "develop", or 
# if there is a change in pyproject.toml dependencies, or Dockerfile, or docker workflow. 

on:
  push:
    paths:
      - '.github/workflows/docker-image.yml'
      - 'pyproject.toml'
      - 'Dockerfile'
    branches:
      - "develop"

  # allows to manually start a workflow run from the GitHub UI or using the GitHub API.    
  workflow_dispatch:

jobs:
  built:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Build the docker image
        run: docker build --tag ai4eu_server_demo:latest -f Dockerfile .
      
      - name: Run docker container and pytest tests
        run: |
          docker run -e KEYCLOAK_CLIENT_SECRET="mocked_secret" --entrypoint "" ai4eu_server_demo sh -c "pip install \".[dev]\" && pytest tests -s"
  
  
          
  
  
    


