name: Docker Image CI 

on:
  push:
    paths:
      - '.github/workflows/docker-image.yml'
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  built:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build --tag ghcr.io/aiondemand/ai4eu_server_demo:latest -f Dockerfile .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.github_token }}
          
      - name: Push the docker Image
        run: | 
          docker push ghcr.io/aiondemand/ai4eu_server_demo:latest
  
  
          
  
  
    


